# Generated by Django 6.0.4 on 2026-04-28 12:13

import trainer_applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('expertise', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=500)),
                ('course_idea', models.TextField()),
                ('cv_file', models.FileField(upload_to='applications/cv/', validators=[trainer_applications.models.validate_file_size, trainer_applications.models.validate_cv_extension])),
                ('cert_1', models.FileField(blank=True, upload_to='applications/certs/', validators=[trainer_applications.models.validate_file_size, trainer_applications.models.validate_certificate_extension])),
                ('cert_2', models.FileField(blank=True, upload_to='applications/certs/', validators=[trainer_applications.models.validate_file_size, trainer_applications.models.validate_certificate_extension])),
                ('cert_3', models.FileField(blank=True, upload_to='applications/certs/', validators=[trainer_applications.models.validate_file_size, trainer_applications.models.validate_certificate_extension])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
